{% set name = 'qsvlite' %}
{% set version = "0.69.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/jqnatividad/qsv/archive/{{ version }}.tar.gz
  sha256: 8a4c29c4253afe2265349b735abe052c8c4e677572e4c1826117a51009cdec76

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - cargo-bundle-licenses

test:
  commands:
    - qsvlite --help

about:
  home: https://github.com/jqnatividad/qsv/
  license: MIT
  summary: CSVs sliced, diced & analyzed.
  license_family: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - adRn-s
